version: "3"
services:
    web:
        build: 
            context: .
            dockerfile: FirstDemo.Web/Dockerfile
        image: devskill/firstdemo.web
        env_file: 
            - FirstDemo.Web/web.env
        volumes:
            - firstdemoweb-data:/app/Logs
        ports:
            - "8000:80"
        entrypoint: ["dotnet", "FirstDemo.Web.dll"]
volumes:
    firstdemoweb-data:
      external: true
     